Propagate anyhow errors all the way to main
If the main function returns an error, it will be nicely printed for the user.

Previously the error looked like this:
thread 'main' panicked at 'Unable to build package in PKGBUILDS/sxmo/lisgd', src/main.rs:262:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

With the patch it looks like this:
Error: Unable to build package in PKGBUILDS/sxmo/lisgd

Caused by:
    0: Unable to copy file "/tmp/guzuta-pkgdest.ktzooXxar6Dx/lisgd-0.3.2-1-x86_64.pkg.tar.zst" to "./repo/sxmo/x86_64/lisgd-0.3.2-1-x86_64.pkg.tar.zst"
    1: No such file or directory (os error 2)